./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/615 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/615 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/615 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/615 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/615 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/615 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/615 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/615 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/615 BiH &
