./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/1122 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/1122 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/1122 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/1122 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/1122 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/1122 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/1122 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/1122 BiH &
./phantomjs openBrowser.js http://dugokontov.noip.me/#/project/1122 BiH &
